services:
  api:
    build:
      context: .
    container_name: python-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=api_flask
      - MYSQL_URL=mysql+pymysql://root:123456@mysqldb:3306/api_flask
    volumes:
      - .:/api
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    container_name: mysql-api
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=api_flask
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:

networks:
  default:
    external:
      name: epo2-net