services:
  api:
    build:
      context: .
    container_name: python-api
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_URL=mysql+pymysql://root:123456@mysqldb:3306/flask
    volumes:
      - .:/api
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0.2
    container_name: mysql-api
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=flask
    ports:
      - "3608:3306"
    volumes:
      - db_api:/var/lib/mysql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
volumes:
  db_api:
networks:
  default:
    external:
      name: epo2-net